:- module(test_differential, []).

%% The enumeration differential as a test. With every profile in force,
%% Hornguard must never admit a predicate SWI's own sandbox refuses, and
%% every sandbox-safe predicate Hornguard refuses must be explained by a
%% pin or by the generator's exclusion table. A new engine version that
%% changes a builtin's character shows up here first.

:- use_module(library(plunit)).
:- use_module(library(lists)).
:- use_module(library(apply)).
:- use_module('../prolog/hornguard').
:- use_module('../tools/differential').
:- use_module('../tools/gen_swi_profiles').

:- dynamic report/1.

ensure_report :-
    (   report(_)
    ->  true
    ;   all_profiles(Ps),
        differential_report(Ps, R),
        assertz(report(R))
    ).

of_kind(Kind, K-_-_) :- K == Kind.

explained(N/A) :- hornguard:hg_pinned(_, N/A), !.
explained(Ind)  :- hornguard_gen_swi_profiles:exclude(Ind, _), !.

:- begin_tests(differential).

test(no_hole_candidates, [true(Holes == [])]) :-
    ensure_report, report(R),
    include(of_kind(hole_candidate), R, Holes).

test(every_refusal_of_a_sandbox_safe_predicate_is_explained, [true(Unexplained == [])]) :-
    ensure_report, report(R),
    include(of_kind(profile_todo), R, Todo),
    findall(Ind, ( member(_-Ind-_, Todo), \+ explained(Ind) ), Unexplained).

test(undecided_are_only_closure_arity, [true(Other == [])]) :-
    ensure_report, report(R),
    include(of_kind(undecided), R, Und),
    findall(Ind-D, ( member(_-Ind-D, Und), D \== closure_arity_above_2 ), Other).

test(generated_profiles_are_current, [true(Same == true)]) :-
    % Regenerating must reproduce the committed file (modulo the date line).
    tmp_file(swi_profile, Tmp),
    gen_swi_profiles(Tmp),
    read_file_to_string('profiles/swi.pl', S0, []),
    read_file_to_string(Tmp, S1, []),
    delete_file(Tmp),
    strip_date(S0, T0), strip_date(S1, T1),
    ( T0 == T1 -> Same = true ; Same = false ).

:- end_tests(differential).

strip_date(S, T) :-
    split_string(S, "\n", "", Lines),
    exclude([L]>>sub_string(L, _, _, _, "GENERATED by"), Lines, Kept),
    atomic_list_concat(Kept, '\n', T).
